### ISSUE TITLE
[JavaScript] Security warnings

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1126]
The [GitHub security alerts page](https://github.com/exercism/v3/network/alerts) shows that there are several exercises that have a security risk. These should be fixed.

**Comment by SleeplessByte** [comment]
I don't have access to that page, so I can't fix them either. 

Note that security risk is _not_ security vulnerability.

**Comment by ErikSchierboom** [comment]
![image](https://user-images.githubusercontent.com/135246/78996431-e2209480-7b44-11ea-8ec9-90d7e2e9e007.png)

True, but there are high risk entries.

**Comment by SleeplessByte** [comment]
Making them high risk still doesn't mean they're applicable to us, at all. 

For example, `minimist`: https://github.com/advisories/GHSA-vh95-rmgr-6w4m

This one _requires_ you to be able to craft a special payload and send that to `minimist` which is only used in `mkdirp`. Nowhere in the code do we currently allow "user payloads" to be sent to `mkdirp`.

So should it be fixed? Sure. Is it important to fix asap (as in, does the label match how we should feel about it)? No, because the attack surface is non-existent for us.

**Comment by ErikSchierboom** [comment]
Okay, thanks for explaining. Someone can fix these when they have time then.
