### ISSUE TITLE
[Go] Missing exercise entries in config.json

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3#1703]
The track's `config.json` file is missing an entry for the following exercise:

- ` basics`
- `conditionals`
- `errors`
- `maps`

**Comment by ErikSchierboom** [comment]
FYI @exercism/go

**Comment by oanaOM** [comment]
I would be glad to add them.

**Comment by tehsphinx** [comment]
@oanaOM: go ahead! 💟

**Comment by oanaOM** [comment]
Great, I've just open a PR.

**Comment by tehsphinx** [comment]
@oanaOM: Perfect! I merged it.

If you're up for an extension of this task:

From the `config.json` this tree is now being generated: https://v3.exercism.io/go/maintaining/tree.

Since the tools are able to check which exercises in `config.json` are actually implemented and which ones are not, it would be nice if we could already put the entire tree into the `config.json` (even though the exercises are not yet implemented).

Currently the tree is [here](https://github.com/exercism/v3/issues/212) in a picture which is not interactive, not always up to date and also not that easy to read.

Also: feel free to improve the exercise tree! It is not set in stone.

**Comment by tehsphinx** [comment]
More notes:
- former "types" is now "basics" exercise... or basics precedes "types"... I'm not sure yet. For now we have removed "types" exercise and replaced it with "basics". We will see if that works.
- "basics" is the first exercise and does not have any prerequisites. Maybe even "comments" should have "basics" as a prerequisite... as we explain very basic things like packages in "basics".

**Comment by oanaOM** [comment]
@tehsphinx I think we are in a good state with the config now. I hope you are ok with closing this for now.

**Comment by ErikSchierboom** [comment]
Yeah sure 👍

**Comment by tehsphinx** [comment]
Thanks a lot, @oanaOM!
