### ISSUE TITLE
[Docs] Methods concept has circular reference

### ISSUE THREAD

**Issue by wolf99** [exercism/v3#183]
The Methods concept https://github.com/exercism/v3/blob/master/reference/concepts/methods.md is defined as `a function that is part of a class`. It links to the function concept (as well as the class concept.

The Function concept however, is defined _using_ "method": `By "functions" we mean functions, methods and procedures.`. This is a circular reference.

To me this is made more confusing by the rest of the function concept which covers what the concept _is not_.

Especially confusing is: `We do not aim to teach: "functions" as the concept of self-contained pieces of functionality` ... If this is not the definition of a function, I'm not sure what is 😄 (unless referring to the term "function" here in the non-programming sense, but that still doesn't help describe "method"... or "function").

**Comment by ErikSchierboom** [comment]
@wolf99 I agreed that this is confusing. Would you be interested in submitting a PR to fix this?

**Comment by wolf99** [comment]
Happy to add a PR. Not fully sure what the intention is regarding the last paragraph of my OP though. Are you or @ccare  able to clarify?

**Comment by iHiD** [comment]
The point the file is trying to make is that tracks should teach how functions are used in languages, not what functions themselves are. So we should presume that someone understands the concept of encapsulation in a body (e.g. function/method/proc) but that they may have no idea about how that specifically applies to a language, and that the Concept Exercise should teach the language-specifics, not the general concepts.

That said, I would love to have a good canonical resource on "What is a function" that we can just have as a hyperlink the first time `function` is mentioned in a Concept Exercise.

(Sidenote, this is probably a question for @ErikSchierboom rather than @ccare. Charles deals with the infrastructure/website side of things, rather than the "curriculum" area.)

**Comment by ErikSchierboom** [comment]
> That said, I would love to have a good canonical resource on "What is a function" that we can just have as a hyperlink the first time function is mentioned in a Concept Exercise.

Yep, this is what I was hinting at. The PR could explain what a function is in language-agnostic terms, which could be used as a reference when developing exercises.

**Comment by trungtjeu** [comment]
Ok   xin chào  mọi người

**Comment by angelikatyborska** [comment]
The conclusion of the related PR is that cycles in concept references are fine: https://github.com/exercism/v3/pull/336#discussion_r404577403
