### ISSUE TITLE
[<Pharo>] Is Pharo not part of V3?

### ISSUE THREAD

**Issue by heshamfm** [exercism/v3#2119]
I originally came to ask a question about importing Pharo example files of two-fer into Pharo image. But, I noticed that Pharo was not listed as a language in v3.

Is it true that Pharo Smalltalk will not be part of exercism v3?

If the issue is not finding enough contributors, then we could probably get help from the community. If it is a market demand issue, I could only claim that Pharo is very promising. 

#Pharo #Smalltalk

**Comment by iHiD** [comment]
I don't believe anyone has started that process yet. There was discussion [here](https://github.com/exercism/pharo-smalltalk/issues/411) but I'm not sure it came to anything. The other person in that discussion has since deleted their GH account.

So there are two options:
1. Become a proper v3 track with concept exercises etc
2. Become a sort of legacy track in v3, with just practice exercises.

I'd love to see Pharo fall into the (1) category - it will just need a couple of people to take the reins to make that happen.

(cc @samWson)

**Comment by samWson** [comment]
Hi @heshamfm. I've been trying to keep the Pharo Smalltalk track going but I just don't have the time to dedicate to it. Making Pharo a v3 track just isn't on my road map since I can barely maintain what's already there. Getting new contributors would be great but there is a lot of custom code written to make working with exercism from the Pharo image possible and I don't have a good understanding of it all.

At the moment I'm working on making it easier for other people to contribute exercises and maintain the code. However it's slow going and I can only dedicate a few hours a week to it at best.

**Comment by RoelofWobben** [comment]
and I  wait till SamWson and I figured out how to make the new format and what to change in the V3

**Comment by heshamfm** [comment]
Thank you @iHiD . I really wish I was good enough to contribute, but I am still a beginner in Pharo. However, I love it so much that I am so keep to see it in V3. Let me ask a question to you gentlemen @samWson and @RoelofWobben what will happen if V3 goes live without Pharo. Can it be migrated later. And will the old version of Exercism continue to exist for people to practice Pharo?

**Comment by RoelofWobben** [comment]
as far as I know and understand  pharo will be in v3 but then not with the full experience of v3. 
@iHiD  maybe you can tell more about this

**Comment by iHiD** [comment]
The Pharo track will still be available. The level of the experience will be determinate on whether the Pharo maintainers can create a Test Runner and Concept Exercises.
