### ISSUE TITLE
[CI] Link verifier should check all files before failing

### ISSUE THREAD

**Issue by SaschaMann** [exercism/v3#2538]
It's annoying to have to run it over and over again.

**Comment by ErikSchierboom** [comment]
We're currently using [this library](https://github.com/tcort/markdown-link-check#command-line-tool). Looking at the install command and the logs, we are running the latest version of the tool. The docs don't mention anything in particular about being able to check multiple files, which is why we have [the following code](https://github.com/exercism/v3/blob/master/.github/workflows/valid-links.yml#L42):

```bash
for file in $files; do
  if [ -f "$file" ]
  then
    markdown-link-check -q -c .github/markdown-link-check-config.json "$file"
  fi
done
```

I assume that when one link fails, the exit code is non-zero and the workflow stops. I think with a bit of bash-fu this should be able to be fixed relatively easily.

**Comment by ynfle** [comment]
For the Nim CI I did [this](https://github.com/exercism/v3/blob/master/.github/workflows/nim-ci.yml#L39-L49) which basically adds the error codes together.
