### ISSUE TITLE
CI should run only on files affected by a PR

### ISSUE THREAD

**Issue by coriolinus** [exercism/v3#2862]
Right now, there are four non-required CI checks which reliably fail for every PR, because they are global checks and some files, not touched by the PR, are consistently wrong. This is bad practice: it trains everyone to just ignore those checks.

Filtering the checks to files touched by a given PR isn't particularly hard; [here's how it's done in the Rust track](https://github.com/exercism/rust/blob/3543b7eb64b12d6f6da0ae722324a9602c21d676/_test/check-exercises.sh#L31-L35).

Filtering the checks to files touched by a given PR means that the check can become mandatory. A mandatory check is strictly better than an optional one: it requires fewer judgment calls.

**Comment by efx** [comment]
I agree and have found this confusing as I start contributing to the v3 effort again.
I would like to know if the markdown I introduce for Rust documents has issues. Instead I see that multiple other tracks have linting issues and it distracts me focusing on what the Rust track needs.

**Comment by SaschaMann** [comment]
As a general note, I think global checks are to be preferred unless they take too long. If master is green, a failure must've been introduced in the PR anyway. It's more robust. Some checks that only ran on changed files before ended up failing on master despite being green in the PR.

Those checks were expected to fail as a temporary annoyance until all tracks created those files (that plan didn't work so well because ignoring the checks lead to more missing files over time 🤷).

**Comment by efx** [comment]
My practical need has been addressed. I had not realized the master branch had fixes. I do not have a strong opinion here so will defer to @SaschaMann since he maintains the CI.

**Comment by iHiD** [comment]
Closing this as this repo is now closing.
