### ISSUE TITLE
[Elixir] Extract Concepts from v2 exercise: bowling

### ISSUE THREAD

**Issue by nathanchere** [exercism/v3#737]
Extract the list of concepts required to solve the v2 Elixir exercise: `bowling`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/bowling/solutions`). The goal of this task is to help determine the total list of concepts that make up `bowling`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/bowling.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/bowling.md

**Comment by neenjaw** [comment]
@nathanchere is there a PR for this yet?

**Comment by nathanchere** [comment]
Hey, I have gone through and pulled out what I think are the relevant concepts in a doc but when I went to look at another PR to see how to submit the information I saw they also included example solutions so I was holding off until I could go through and do the same for each one. If we're past that point and there's really no value in doing that too I can just add them as-is, otherwise I can have the PR still submitted this week.

**Comment by neenjaw** [comment]
Any insights you have into the problem and what concepts are flushed out with it are always useful!

My thought was that if you hadn't had a chance to work on it because life then you could short circuit to the next step since I think we need to start deciding on our concept progression, and to write out exercise specs (either applying exercises from other track's to ours, or developing the narrative for our own)

---

If you have concepts to add, there is a PR open from chriseyre which you could comment on with your additions then I can push them to the PR branch

If you have the other write up complete, you can contribute that too. I think people are including solutions (myself included) just to justify the concept inclusion. But not required as far as I am aware.
